/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./../components/index.vue')['default']
    Header: typeof import('./../components/layout/header/Header.vue')['default']
    Layout: typeof import('./../components/layout/Layout.vue')['default']
    MoveMenu: typeof import('./../components/layout/header/MoveMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}
